name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Nginx image
      run: docker build . --file Dockerfile --tag nikita9951/nginx-image-autobuild:latest
    - name: Push the Nginx image
      run: docker login -u nikita9951 -P ${{ secrets.DOCKER_TOKEN }} && docker push nikita9951/nginx-image-autobuild:latest
